### PR TITLE
Fix scenario where first loaded from another dir

### PR DESCRIPTION
**Pull request by jupiter**
This fixes the additional scenario provided by @perrin4869 https://github.com/perrin4869/decache_poc/commit/444528a2c8715ac1b1875e7823f354d695e3b71d

### CODE REVIEW

**Comment by jupiter** [comment]
In relation to #21

**Comment by perrin4869** [comment]
@jupiter I really thought it was not possible to support relative decache but you got it :D
I think this is it!

**Comment by jupiter** [comment]
@nelsonic Any opposition?

**Comment by nelsonic** [comment]
Looks great! (_no opposition whatsoever!_) 🎉 
merged! Thanks!! 🚀

**Comment by nelsonic** [comment]
@perrin4869 + @jupiter `decache@4.1.0` on NPM support the latest improvements. thanks again! ⭐

**Pull request merged**
